### ISSUE TITLE
"Requirements not installed." Error

### ISSUE THREAD

**Issue by JoschD** [rdemaria/pjlsa#11]
Hey,
I am getting a "Requirements not installed." message, followed by an error, that pjlsa.LSAClient was not found. 
This message could be a bit less cryptic: I guess it comes from `__init__.py` and refers to the fact, that the JARs are not properly installed.

What is the easiest way, to install the proper java dependencies for pjlsa?
I have it running on one machine, as there I had `eclipse + a package that depends on LSA + running cmmnbuild-ng build` which I guess installed everything I needed, but that seems overly complicated for a fresh install on a new machine, where I only need the python tools.

Thank you very much!
Bests,
Joschua

**Comment by rdemaria** [comment]
You only need Java 1.8 and `pip install pjlsa` should install correctly. The errors is typically triggered when the jars needed by pjlsa were not downloaded during installation for some reason.

Can you check which java version you have?

**Comment by JoschD** [comment]
Thank you very much for the quick answer and for the personal help.
For reference: The problem was, that the cmmnbuild-dep-manager had not properly registered pjlsa and hence not installed the jars (for yet unknown reasons). 

Check:
```python
import cmmnbuild_dep_manager
mgr = cmmnbuild_dep_manager.Manager()
mgr.list()
```

The list should contain `pjlsa`,  which it didn't in my case.

Solution:
```python
import pjlsa
mgr.register('pjlsa')
mgr.resolve()
```
